### ISSUE TITLE
API Key Request Failure on Email Input

### ISSUE THREAD

**Issue by Moamethic** [Sinaptik-AI/panda-etl#13]
When attempting to use the program after installation, entering an email address in the input field results in the error message: "Failed to request API key. Please try again."

**Steps to Reproduce**
1- Install the program following the provided instructions
2- Launch the program
3- Locate the email input field
4- Enter a valid email address
5- Submit the email or proceed to the next step

**Expected Behavior**
The program should accept the email and successfully request an API key.
**Actual Behavior**
The program displays the error message: "Failed to request API key. Please try again."

**Additional Information**
This issue persists across different environments
All installation steps were followed correctly according to the provided instructions

**Comment by dSupertramp** [comment]
What email did you use?

**Comment by Moamethic** [comment]
moamethic@gmail.com

**Comment by dSupertramp** [comment]
Did you correctly copy the .env files? There are two of them, one in the `backend` folder and one in the `frontend` folder

**Comment by Moamethic** [comment]
Yes I did.

**Comment by dSupertramp** [comment]
You can try to follow my procedure:
- I use VS Code and I open two terminals (I'm using Ubuntu)
- In the first one, go to `backend` folder, cp .env, create a virtualenv with Python 3.11 and run the commands 

`poetry install -> make migrate -> make run`

- In the second one, go to `frontend` folder, cp .env, 

`yarn install -> yarn dev`

**Comment by Moamethic** [comment]
I exactly did the same procedure using tmux in linux.

**Comment by ArslanSaleem** [comment]
@Moamethic can you please share the screen short for backend server console, .log file and also share .env files that you are using?

It would be helpful to figure out the issue you are facing. Thanks
