### ISSUE TITLE
Add support for .xlsx (Excel) files

### ISSUE THREAD

**Issue by dSupertramp** [Sinaptik-AI/panda-etl#14]
I'm trying to add the support to handle Excel file, but I feel a little bit lost: can someone provide me some guidance? Thanks!

**Comment by ArslanSaleem** [comment]
Hi @dSupertramp , probably this might come in future but at the moment the platform is for unstructured data. If you are interested in structured data you can look into https://github.com/Sinaptik-AI/pandas-ai.

**Comment by dSupertramp** [comment]
Yeah I already know pandas-ai: what kind of unstructured data we can add apart PDF?

**Comment by ArslanSaleem** [comment]
> Yeah I already know pandas-ai: what kind of unstructured data we can add apart PDF?

Website links, .docx, .ppt etc.
