### ISSUE TITLE
Api key is not sent email

### ISSUE THREAD

**Issue by Challagullanagsrujan** [Sinaptik-AI/panda-etl#20]
i did all procedure mentioned in readme file but when i visit http://localhost:3000/  it asking email when i submit it it is directed to api page but api is not sent to email

**Comment by gventuri** [comment]
@Challagullanagsrujan which email provider are you using? Did you check the spam folder?

@ArslanSaleem can help you with that in case you need to debug further!

**Comment by Challagullanagsrujan** [comment]
Yes I checked smap folder

**Comment by Challagullanagsrujan** [comment]
challagullanagsrujan8088@gmail.com
