### ISSUE TITLE
Why do we need to send the data to this API endpoint by default? Can't we use any other LLM model ?

### ISSUE THREAD

**Issue by natarajan0007** [Sinaptik-AI/panda-etl#31]
PANDAETL_SERVER_URL="https://api.panda-etl.ai/" # optional
API_SERVER_URL="https://api.domer.ai" # optional

**Comment by gventuri** [comment]
@natarajan0007 it is using 2 endpoints, one for parsing and one for extracting. If you want, you can try to recreate endpoint with similar features and change the url to use your endpoints though!

**Comment by volethanh** [comment]
> @natarajan0007 it is using 2 endpoints, one for parsing and one for extracting. If you want, you can try to recreate endpoint with similar features and change the url to use your endpoints though!

I thought this is panda-etl opensource and it includes all this so we can deploy as self-hosted instead of we have to get api and only use 1000 credits per month

**Comment by natarajan0007** [comment]
I built a similar endpoint using fast api powered by vertex ai ( Gemini) model which exactly same thing . But I am not using chat interface which was provided by them . I used my custom built.

**Comment by volethanh** [comment]
I also focus on the backend too, but the first step when I run this, i wonder about using both of the api, same questions as you

**Comment by natarajan0007** [comment]
I uses some sample pdf documents on the internet.so I don't mind it for testing. Just wanted to see how we parsing the data whenever user chat with beta bot. In my original application i removed these pandasai urls and pointed to my backend.

**Comment by volethanh** [comment]
it means that you have to implement 2 new endpoints in your backend and then you point the config in .env to that ?

**Comment by natarajan0007** [comment]
You only need one . You can ignore API key endpoint. They wanted to protect their endpoints that's why they used two. You handle API keys in the same fast api itself rather then creating two .

**Comment by volethanh** [comment]
thanks for your information. Do You have snipping code that simulate parsing and extracting same thing like that ?

**Comment by natarajan0007** [comment]
Ideally if you debug the post call they are making to padasai api you know how they are parsing the whole documents chunks . You need to handle this in your backend with any LLM model which you wanted to parse the context and provide response back .

**Comment by volethanh** [comment]
Ok i’ll try. thanks again
